--PROCEDIMIENTOS Y FUNCIONES
DROP PROCEDURE [ABSTRACCIONX4].AltaRol
DROP PROCEDURE [ABSTRACCIONX4].AltaFuncionalidad
DROP FUNCTION [ABSTRACCIONX4].DarCodigoDeRol
DROP FUNCTION [ABSTRACCIONX4].DarCodigoDeFuncionalidad
DROP PROCEDURE [ABSTRACCIONX4].BajaRol
DROP PROCEDURE [ABSTRACCIONX4].ModificarRol
DROP PROCEDURE [ABSTRACCIONX4].BajaFuncionalidades
DROP PROCEDURE [ABSTRACCIONX4].AltaAeronave
DROP PROCEDURE [ABSTRACCIONX4].DejarAeronaveFueraDeServicio
DROP PROCEDURE [ABSTRACCIONX4].DarDeBajaLogica
DROP PROCEDURE [ABSTRACCIONX4].ModificarAeronave
DROP FUNCTION [ABSTRACCIONX4].TieneViajeAsignado
DROP PROCEDURE [ABSTRACCIONX4].AltaRuta
DROP FUNCTION [ABSTRACCIONX4].ObtenerCodigoCiudad
DROP FUNCTION [ABSTRACCIONX4].ObtenerCodigoServicio
DROP PROCEDURE [ABSTRACCIONX4].BajaRuta
DROP PROCEDURE [ABSTRACCIONX4].BorrarEncomiendas
DROP PROCEDURE [ABSTRACCIONX4].ModificarRuta
DROP TYPE [ABSTRACCIONX4].Lista
DROP TRIGGER [ABSTRACCIONX4].ModificarMatricula
DROP TRIGGER [ABSTRACCIONX4].ModificacionButaca
DROP PROCEDURE  [ABSTRACCIONX4].ModificarAeronavePasajes 
DROP PROCEDURE  [ABSTRACCIONX4].ModificarAeronaveEncomiendas
DROP PROCEDURE  [ABSTRACCIONX4].ModificarAeronaveButacas
DROP PROCEDURE  [ABSTRACCIONX4].ModificarAeronaveViajes

drop procedure [ABSTRACCIONX4].crearTablaFecha
drop function [ABSTRACCIONX4].obtenerFechaDeHoy


--TABLAS DE LA BASE
DROP TABLE [ABSTRACCIONX4].FUNCIONES_ROLES
DROP TABLE [ABSTRACCIONX4].DEVOLUCIONES
DROP TABLE [ABSTRACCIONX4].ROLES_USUARIOS
DROP TABLE [ABSTRACCIONX4].USUARIOS
DROP TABLE [ABSTRACCIONX4].ROLES
DROP TABLE [ABSTRACCIONX4].PASAJES
DROP TABLE [ABSTRACCIONX4].FUNCIONALIDADES
DROP TABLE [ABSTRACCIONX4].ENCOMIENDAS
DROP TABLE [ABSTRACCIONX4].VIAJES
DROP TABLE [ABSTRACCIONX4].COMPRAS
DROP TABLE [ABSTRACCIONX4].CANJES
DROP TABLE [ABSTRACCIONX4].RUTAS_AEREAS
DROP TABLE [ABSTRACCIONX4].TARJETAS
DROP TABLE [ABSTRACCIONX4].PREMIOS
DROP TABLE [ABSTRACCIONX4].CLIENTES
DROP TABLE [ABSTRACCIONX4].BUTACAS
DROP TABLE [ABSTRACCIONX4].AERONAVES
DROP TABLE [ABSTRACCIONX4].SERVICIOS
DROP TABLE [ABSTRACCIONX4].CIUDADES
DROP TABLE [ABSTRACCIONX4].TIPOS_CUOTAS
DROP TABLE [ABSTRACCIONX4].TIPOS
DROP TABLE [ABSTRACCIONX4].DEVOLUCIONES
DROP TABLE ABSTRACCIONX4.FECHA
DROP TABLE ABSTRACCIONX4.PRUEBA




