-- INSERTS DE PRUEBA
-- 

INSERT INTO [ABSTRACCIONX4].USUARIOS (USERNAME,PASSWORD) VALUES ('INVITADO', ' ')
INSERT INTO [ABSTRACCIONX4].USUARIOS (USERNAME,PASSWORD) VALUES ('ADMINISTRADOR', 'ABCDEFGH')

INSERT INTO [ABSTRACCIONX4].ROLES (ROL_NOMBRE) VALUES ('Cliente')
INSERT INTO [ABSTRACCIONX4].ROLES (ROL_NOMBRE) VALUES ('Aministrador')
INSERT INTO [ABSTRACCIONX4].ROLES (ROL_NOMBRE) VALUES ('ABM Manager')
INSERT INTO [ABSTRACCIONX4].ROLES (ROL_NOMBRE) VALUES ('Vendedor')

INSERT INTO [ABSTRACCIONX4].ROLES_USUARIOS (USERNAME,ROL_COD) VALUES ('INVITADO',10)
INSERT INTO [ABSTRACCIONX4].ROLES_USUARIOS (USERNAME,ROL_COD) VALUES ('INVITADO',12)
INSERT INTO [ABSTRACCIONX4].ROLES_USUARIOS (USERNAME,ROL_COD) VALUES ('INVITADO',13)
INSERT INTO [ABSTRACCIONX4].ROLES_USUARIOS (USERNAME,ROL_COD) VALUES ('ADMINISTRADOR',11)


SELECT * FROM ABSTRACCIONX4.ROLES_USUARIOS


GO

-------------------------------Trigger de insert en usuario que encripta el password-------------------------------
/*CREATE TRIGGER insertUsuario
ON [ABSTRACCIONX4].USUARIOS
INSTEAD OF INSERT
AS
BEGIN
	DECLARE @Usuario VARCHAR(20)
	DECLARE @Password VARCHAR(70)
	
	SELECT @Usuario = USERNAME, @Password = PASSWORD
		FROM [ABSTRACCIONX4].USUARIOS

	IF @Usuario = 'INVITADO'
		RETURN


END

GO*/

insert into ABSTRACCIONX4.FUNCIONALIDADES (FUNC_DESC) values ('ABM Rol')
insert into ABSTRACCIONX4.FUNCIONALIDADES (FUNC_DESC) values ('ABM Aeronave')
insert into ABSTRACCIONX4.FUNCIONALIDADES (FUNC_DESC) values ('ABM Ruta')