CREATE PROCEDURE [ABSTRACCIONX4].RegistrarUsuario
(@Usuario VARCHAR(20),@Contrasenia VARCHAR(70))
AS
BEGIN
	BEGIN TRY
		INSERT INTO ABSTRACCIONX4.USUARIOS (USERNAME,PASSWORD)
			VALUES (@Usuario,@Contrasenia)
		INSERT INTO ABSTRACCIONX4.ROLES_USUARIOS (USERNAME,ROL_COD)
			SELECT @Usuario,ROL_COD
				FROM ABSTRACCIONX4.ROLES 
				WHERE ROL_NOMBRE = 'ADMINISTRADOR'
	END TRY
	BEGIN CATCH
		DECLARE @Error varchar(80)
		SET @Error = 'El nombre de usuario ' + @Usuario + ' ya existe.'
		RAISERROR(@Error, 16, 1)
	END CATCH
END

